# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: JavaScript Tests, Lint, and Coverage
on:
  push:
    paths:
      - 'js/**'
    #TODO Later: I think this workflow will also fire for any tags, which seems a bit wasteful?
  pull_request:
    paths:
      - 'js/**'
jobs:
  tests:
    name: Node 20 on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # https://github.com/actions/setup-node#caching-global-packages-data
          cache: npm
          cache-dependency-path: js/package-lock.json
      - name: Install dependencies
        working-directory: ./js
        run: npm ci
      - name: Tests incl. lint and coverage
        working-directory: ./js
        run: npm test
