# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Perl Basic Tests (only)
on:
  push:
    paths:
      - 'pl/**'
    # since this already fires for each push, no need to fire for tags too:
    #tags-ignore: '**'
    # TODO: I think this now casued the workflow to not run at all? I guess
    # I need to read up on actions a bit more.
  pull_request:
    paths:
      - 'pl/**'
jobs:
  tests:
    # Uses the Perl that comes preinstalled on all GH Action runners
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    name: Default Perl on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        working-directory: ./pl
        run: prove -l
